name: example

on: push

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Saying hi
        run: echo "This is the first step of my first job."
  
  test-python-3-10:
    runs-on: ubuntu-latest
    name: Check Python 3.10 on Ubuntu
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: python --version