name: example

on: push

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Saying hi
        run: echo "This is the first step of my first job."
  
      - name: Install something
        run: apt install imagemagick
